/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ninja.dme.alcor;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void testAppHasAGreeting() {
        //MoonPhase classUnderTest = new MoonPhase();
        //assertNotNull("app should have a greeting", classUnderTest.ping());
    }
}
